In [4]:
import numpy as np
import pandas as pd

In [5]:
df_train=pd.read_csv(r"C:\Users\anhsu\Downloads\lab3\lab3\data\train_data.csv")
df_test=pd.read_csv(r"C:\Users\anhsu\Downloads\lab3\lab3\data\test_data.csv")

In [8]:
df_train

AccX      AccY      AccZ     GyroX     GyroY     GyroZ   Class  \
0     0.000000  0.000000  0.000000  0.059407 -0.174707  0.101938  NORMAL   
1    -1.624864 -1.082492 -0.204183 -0.028558  0.051313  0.135536  NORMAL   
2    -0.594660 -0.122410  0.220502 -0.019395 -0.029322  0.087888  NORMAL   
3     0.738478 -0.228456  0.667732  0.069791 -0.029932  0.054902  NORMAL   
4     0.101741  0.777568 -0.066730  0.030696 -0.003665  0.054902  NORMAL   
...        ...       ...       ...       ...       ...       ...     ...   
3639  0.915688 -2.017489  1.687505  0.450360  0.384845 -1.236468    SLOW   
3640 -1.934203  0.914925 -0.096013  0.321468  0.649350 -0.477162    SLOW   
3641 -0.222845  0.747304 -0.887430  0.361174 -0.406836  0.054291    SLOW   
3642 -0.349423  0.067261  0.394368 -0.132405  0.020159 -0.004963    SLOW   
3643 -0.402428  0.406218 -0.423009 -0.053603 -0.006720  0.001145    SLOW   

      Timestamp  
0       3581629  
1       3581630  
2       3581630  
3       3581631  
4       3581631  
...         ...  
3639    3583789  
3640    3583790  
3641    3583790  
3642    3583791  
3643    3583791  

[3644 rows x 8 columns]

In [9]:
df_train.drop(['Timestamp'], axis=1, inplace=True)
df_test.drop(['Timestamp'], axis=1, inplace=True)

In [10]:
print(df_train['Class'].unique())
print(df_test['Class'].unique())

['NORMAL' 'AGGRESSIVE' 'SLOW']
['AGGRESSIVE' 'NORMAL' 'SLOW']


In [11]:
df_train['Class']=df_train['Class'].replace(['NORMAL', 'SLOW', 'AGGRESSIVE'],[0, 0, 1])
df_test['Class']=df_test['Class'].replace(['NORMAL', 'SLOW', 'AGGRESSIVE'],[0, 0, 1])

In [14]:
X_train = df_train[['AccX', 'AccY', 'AccZ', 'GyroX', 'GyroY', 'GyroZ']]
X_test = df_test[['AccX', 'AccY', 'AccZ', 'GyroX', 'GyroY', 'GyroZ']]
y_train = df_train[['Class']].values.ravel()
y_test = df_test[['Class']].values.ravel()

In [16]:
from sklearn import svm
clf=svm.SVC()
clf.fit(X_train,y_train)

SVC()

In [17]:
clf.support_vectors_

array([[ 0.        ,  0.        ,  0.        ,  0.05940665, -0.17470746,
         0.10193814],
       [-0.5946599 , -0.12240987,  0.2205019 , -0.01939497, -0.02932153,
         0.08788824],
       [ 0.30885077,  0.23902233,  1.5170336 , -0.02916882,  0.15943582,
        -0.07276932],
       ...,
       [ 0.32343265,  0.58931136, -1.9397969 , -0.02794708,  1.255328  ,
         0.63949955],
       [ 2.4973106 , -0.6061754 ,  4.7001543 ,  0.8492554 , -0.1966986 ,
        -0.24075727],
       [ 0.4822966 , -0.0902772 , -1.1656733 , -0.5581781 , -0.24251351,
        -0.38369974]])

In [18]:
clf.score(X_test, y_test)


0.7590791180285343

In [19]:
clf.predict(X_test)

array([0, 0, 1, ..., 1, 0, 0], dtype=int64)

### A4

In [22]:
clf=svm.SVC(kernel='linear')
clf.fit(X_train,y_train)
clf.support_vectors_
clf.score(X_test, y_test)
clf.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [23]:
clf=svm.SVC(kernel='poly')
clf.fit(X_train,y_train)
clf.support_vectors_
clf.score(X_test, y_test)
clf.predict(X_test)

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [26]:
clf=svm.SVC(kernel='rbf')
clf.fit(X_train,y_train)
clf.support_vectors_
clf.score(X_test, y_test)
clf.predict(X_test)



array([0, 0, 1, ..., 1, 0, 0], dtype=int64)

In [28]:
clf=svm.SVC(kernel='sigmoid')
clf.fit(X_train,y_train)
clf.support_vectors_
clf.score(X_test, y_test)
clf.predict(X_test)


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)